version: '3.9'

services:
# Сервис для разворачивания контейнера с базой данных
  database:
    image: postgres:latest
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=us_delivery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123


# Сервис для разворачивания контейнера с приложением
  webapi:
    container_name: webapi
    build: .
    command: bash -c "python sql/models.py createdb && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: always
    environment:
      - POSTGRESQL_CONFIG=postgresql+psycopg2://postgres:123@database/us_delivery
